version: '3.7'

services:
  spring-boot-maven-api:
    image: postgres:14.1-alpine
    container_name: spring-boot-maven-api
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5441:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data