version: '3.7'

services:
  spring-boot-maven-api:
    image: postgres
    container_name: spring-boot-maven-api
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5441:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data